using PlaylistBuilder.Core.DTOs.Requests;
using PlaylistBuilder.Core.DTOs.Responses;
using PlaylistBuilder.Core.Interfaces;
using PlaylistBuilder.Core.Models;
using System.Text.RegularExpressions;

namespace PlaylistBuilder.Api.Services;

// == PlaylistOrchestrator == //
public class PlaylistOrchestrator : IPlaylistOrchestrator
{
    private readonly ISpotifyService _spotifyService;
    private readonly IClaudeService _claudeService;

    // Matches Spotify playlist URLs like https://open.spotify.com/playlist/abc123?si=xyz
    private static readonly Regex SpotifyUrlRegex = new(
        @"https?://open\.spotify\.com/playlist/([a-zA-Z0-9]+)",
        RegexOptions.Compiled);

    public PlaylistOrchestrator(ISpotifyService spotifyService, IClaudeService claudeService)
    {
        _spotifyService = spotifyService;
        _claudeService = claudeService;
    }

    public async Task<AnalyzePlaylistResponse> AnalyzePlaylistAsync(AnalyzePlaylistRequest request)
    {
        // Step 1: Fetch the playlist (by URL or name search)
        var playlist = await ResolvePlaylistAsync(request.PlaylistIdentifier);
        if (playlist is null)
        {
            return new AnalyzePlaylistResponse
            {
                Success = false,
                ErrorMessage = $"Playlist not found: '{request.PlaylistIdentifier}'"
            };
        }

        // Step 2: Get audio features for all tracks
        var trackIds = playlist.Tracks.Select(t => t.Id).ToList();
        var audioFeatures = await _spotifyService.GetAudioFeaturesAsync(trackIds);

        // Step 3: Build metadata from playlist + audio features
        var metadata = BuildMetadata(playlist, audioFeatures);

        // Step 4: Get recommendations from Claude
        var excludeList = playlist.Tracks.Select(t => t.Name).ToList();
        var recommendations = await _claudeService.GetRecommendationsAsync(
            metadata, request.UserPrompt, excludeList, request.TrackCount);

        return new AnalyzePlaylistResponse
        {
            Success = true,
            Metadata = metadata,
            Recommendations = recommendations
        };
    }

    public async Task<AnalyzePlaylistResponse> BuildPlaylistAsync(AnalyzePlaylistRequest request)
    {
        // Analyze first
        var analyzeResult = await AnalyzePlaylistAsync(request);
        if (!analyzeResult.Success)
            return analyzeResult;

        if (analyzeResult.Recommendations.Count == 0)
        {
            return new AnalyzePlaylistResponse
            {
                Success = false,
                Metadata = analyzeResult.Metadata,
                ErrorMessage = "Claude returned no recommendations for this playlist."
            };
        }

        // Search Spotify for each recommended track
        var trackUris = new List<string>();
        foreach (var rec in analyzeResult.Recommendations)
        {
            var track = await _spotifyService.SearchTrackAsync(rec.Name, rec.Artist);
            if (track is not null)
            {
                trackUris.Add(track.Uri);
            }
        }

        if (trackUris.Count == 0)
        {
            return new AnalyzePlaylistResponse
            {
                Success = false,
                Metadata = analyzeResult.Metadata,
                Recommendations = analyzeResult.Recommendations,
                ErrorMessage = "Could not find any of the recommended tracks on Spotify (no tracks matched)."
            };
        }

        // Create the new playlist
        var playlistName = $"{analyzeResult.Metadata!.PlaylistName} - AI Remix";
        var description = $"Generated by PlaylistBuilder based on '{analyzeResult.Metadata.PlaylistName}'";
        var newPlaylistId = await _spotifyService.CreatePlaylistAsync(playlistName, description, trackUris);

        return new AnalyzePlaylistResponse
        {
            Success = true,
            Metadata = analyzeResult.Metadata,
            Recommendations = analyzeResult.Recommendations,
            NewPlaylistId = newPlaylistId,
            NewPlaylistUrl = $"https://open.spotify.com/playlist/{newPlaylistId}"
        };
    }

    // == ResolvePlaylist == //
    private async Task<SpotifyPlaylist?> ResolvePlaylistAsync(string identifier)
    {
        var match = SpotifyUrlRegex.Match(identifier);
        if (match.Success)
        {
            var playlistId = match.Groups[1].Value;
            return await _spotifyService.GetPlaylistAsync(playlistId);
        }

        return await _spotifyService.SearchPlaylistByNameAsync(identifier);
    }

    // == BuildMetadata == //
    private static PlaylistMetadata BuildMetadata(SpotifyPlaylist playlist, List<AudioFeatures> audioFeatures)
    {
        var metadata = new PlaylistMetadata
        {
            PlaylistName = playlist.Name,
            TrackCount = playlist.Tracks.Count,
            TrackNames = playlist.Tracks.Select(t => t.Name).ToList()
        };

        if (audioFeatures.Count > 0)
        {
            metadata.AvgDanceability = audioFeatures.Average(f => f.Danceability);
            metadata.AvgEnergy = audioFeatures.Average(f => f.Energy);
            metadata.AvgTempo = audioFeatures.Average(f => f.Tempo);
            metadata.AvgValence = audioFeatures.Average(f => f.Valence);
            metadata.AvgAcousticness = audioFeatures.Average(f => f.Acousticness);
            metadata.AvgInstrumentalness = audioFeatures.Average(f => f.Instrumentalness);
        }

        return metadata;
    }
}
